### ISSUE TITLE
Recording breaks

### ISSUE THREAD

**Issue by IsidaVR** [Rexee/StreamRecorder#4]
Hi, thanks for you project.
There is an issue, streams breaks recording after thee minutes. I try'ed on Twitch and Picarto. Other sites stops after 30seconds.
Any ways to fix that?
Win 10, vlc, latest livestreamer.

**Comment by Rexee** [comment]
Enable logs and look - whats happened with these streams.

**Comment by IsidaVR** [comment]
Heh, i don't know how, but after enabling logs its actually started to work fine :)
Thanks for respond~
